Add die routine. Fix subshell exiting
The fix is about (... && exit 1) fragments.
These didn't actually interrupt the script.

diff --git a/lightson+ b/lightson+
--- a/lightson+
+++ b/lightson+
@@ -45,6 +45,10 @@ inhibitfile="/tmp/lightsoninhibit-$UID-$realdisp"
 pidfile="/tmp/lightson-$UID-$realdisp.pid"
 
 # YOU SHOULD NOT NEED TO MODIFY ANYTHING BELOW THIS LINE
+die() {
+    echo "$@" >&2
+    exit 1
+}
 
 # pidlocking
 pidcreate() {
@@ -53,8 +57,7 @@ pidcreate() {
         echo "$$" > "$pidfile"
     else
         if [ -d "/proc/$(cat "$pidfile")" ]; then
-            echo "an other instance is running, abort!" >&2
-            exit 1
+            die "Another instance is running, abort!"
         else
             echo "$$" > "$pidfile"
         fi
@@ -68,8 +71,7 @@ pidremove() {
         echo -e "error: \"$pidfile\" is not a file\n" >&2
     else
         if [ "$(cat "$pidfile")" != "$$" ]; then
-            echo "an other instance is running, abort!" >&2
-            exit 1
+            die "Another instance is running, abort!"
         else
             rm "$pidfile"
         fi
@@ -101,8 +103,7 @@ elif [ -e "/usr/bin/xdotool" ]; then
     screensaver="xdofallback"
 else
     screensaver=""
-    echo "No screensaver detected (and no xdotool)"
-    exit 1
+    die "No screensaver detected (and no xdotool)"
 fi
 
 checkFullscreen() {
@@ -280,36 +281,36 @@ help() {
 while [ ! -z $1 ]; do
     case $1 in
        "-d" | "--delay" )
-            [[ $2 = *[^0-9]* ]] && echo "Invalid argument. Time in minutes expected after \"$1\" flag. Got \"$2\" " && exit 1 || delay=$2;;
+            [[ $2 = *[^0-9]* ]] && die "Invalid argument. Time in minutes expected after \"$1\" flag. Got \"$2\" " || delay=$2;;
        "-mp" | "--mplayer" )
-            [[ $2 -eq 1 || $2 -eq 0 ]] && mplayer_detection=$2 || (echo "Invalid argument. 0 or 1 expected after \"$1\" flag." && exit 1);;
+            [[ $2 -eq 1 || $2 -eq 0 ]] && mplayer_detection=$2 || die "Invalid argument. 0 or 1 expected after \"$1\" flag.";;
         "-v" | "--vlc" )
-            [[ $2 -eq 1 || $2 -eq 0 ]] && vlc_detection=$2 || (echo "Invalid argument. 0 or 1 expected after \"$1\" flag." && exit 1);;
+            [[ $2 -eq 1 || $2 -eq 0 ]] && vlc_detection=$2 || die "Invalid argument. 0 or 1 expected after \"$1\" flag.";;
         "-t" | "--totem" )
-            [[ $2 -eq 1 || $2 -eq 0 ]] && totem_detection=$2 || (echo "Invalid argument. 0 or 1 expected after \"$1\" flag." && exit 1);;
+            [[ $2 -eq 1 || $2 -eq 0 ]] && totem_detection=$2 || die "Invalid argument. 0 or 1 expected after \"$1\" flag.";;
         "-ff" | "--firefox-flash" )
-            [[ $2 -eq 1 || $2 -eq 0 ]] && firefox_flash_detection=$2 || (echo "Invalid argument. 0 or 1 expected after \"$1\" flag." && exit 1);;
+            [[ $2 -eq 1 || $2 -eq 0 ]] && firefox_flash_detection=$2 || die "Invalid argument. 0 or 1 expected after \"$1\" flag.";;
         "-cf" | "--chromium-flash" )
-            [[ $2 -eq 1 || $2 -eq 0 ]] && chromium_flash_detection=$2 || (echo "Invalid argument. 0 or 1 expected after \"$1\" flag." && exit 1);;
+            [[ $2 -eq 1 || $2 -eq 0 ]] && chromium_flash_detection=$2 || die "Invalid argument. 0 or 1 expected after \"$1\" flag.";;
         # passing an app name suffices to activate chrome app detection
         "-ca" | "--chrome-app" )
-            [ ! -z $2 ] && (chrome_app_detection=$1 && chrome_app_name="$2") || (echo "Missing argument. Chrome app name expected after \"$1\" flag." && exit 1);;
+            [ ! -z $2 ] && (chrome_app_detection=$1 && chrome_app_name="$2") || die "Missing argument. Chrome app name expected after \"$1\" flag.";;
         "-wf" | "--webkit-flash" )
-            [[ $2 -eq 1 || $2 -eq 0 ]] && webkit_flash_detection=$2 || (echo "Invalid argument. 0 or 1 expected after \"$1\" flag." && exit 1);;
+            [[ $2 -eq 1 || $2 -eq 0 ]] && webkit_flash_detection=$2 || die "Invalid argument. 0 or 1 expected after \"$1\" flag.";;
         "-h5" | "--html5" )
-            [[ $2 -eq 1 || $2 -eq 0 ]] && html5_detection=$2 || (echo "Invalid argument. 0 or 1 expected after \"$1\" flag." && exit 1);;
+            [[ $2 -eq 1 || $2 -eq 0 ]] && html5_detection=$2 || die "Invalid argument. 0 or 1 expected after \"$1\" flag.";;
         "-s" | "--steam" )
-            [[ $2 -eq 1 || $2 -eq 0 ]] && steam_detection=$2 || (echo "Invalid argument. 0 or 1 expected after \"$1\" flag." && exit 1);;
+            [[ $2 -eq 1 || $2 -eq 0 ]] && steam_detection=$2 || die "Invalid argument. 0 or 1 expected after \"$1\" flag.";;
         "-mt" | "--minitube" )
-            [[ $2 -eq 1 || $2 -eq 0 ]] && minitube_detection=$2 || (echo "Invalid argument. 0 or 1 expected after \"$1\" flag." && exit 1);;
+            [[ $2 -eq 1 || $2 -eq 0 ]] && minitube_detection=$2 || die "Invalid argument. 0 or 1 expected after \"$1\" flag.";;
         "-ld" | "--load" )
-            [[ $2 -eq 1 || $2 -eq 0 ]] && load_detection=$2 || (echo "Invalid argument. 0 or 1 expected after \"$1\" flag." && exit 1);;
+            [[ $2 -eq 1 || $2 -eq 0 ]] && load_detection=$2 || die "Invalid argument. 0 or 1 expected after \"$1\" flag.";;
         "-minld" | "--minload" )
-            [[ "$(echo "$(sed 's/ .*$//' /proc/loadavg) > 0" | bc -q)" -eq 1 ]] && minload=$2 || (echo "Invalid argument. >0 expected after \"$1\" flag." && exit 1);;
+            [[ "$(echo "$(sed 's/ .*$//' /proc/loadavg) > 0" | bc -q)" -eq 1 ]] && minload=$2 || die "Invalid argument. >0 expected after \"$1\" flag.";;
         "-h" | "--help" )
             help && exit 0;;
         * )
-            echo "Invalid argument. See -h, --help for more information." && exit 1;;
+            die "Invalid argument. See -h, --help for more information.";;
     esac
     
     # arguments must be always passed in tuples
