Missing '-d' argument & some minor fixes
1. Running "./lightson+.sh 120" yields "Ivalid argument. See -h, --help for more information". This is due to the missing '-d' parameter, which is required if the user wants to set the delay time.
2. Typo: "Ivalid"
3. The script shouldn't need the '.sh' extension. According to Google Shell Style Guide (https://google.github.io/styleguide/shell.xml#File_Extensions): "Executables should have no extension (strongly preferred) or a .sh extension. Libraries must have a .sh extension and should not be executable." Removing the '.sh' extension will make filenames look cleaner while still functioning normally as executables. In the end, this comes down to personal preferences though.

diff --git a/lightson+ b/lightson+
--- a/lightson+
+++ b/lightson+
@@ -16,7 +16,7 @@
 # One of {x, k, gnome-}screensaver must be installed.
 
 # HOW TO USE: 
-# "./lightson+.sh 120 &" will Check every 120 seconds if Mplayer,
+# "./lightson+.sh -d 120 &" will Check every 120 seconds if Mplayer,
 # VLC, Firefox or Chromium are fullscreen and delay screensaver and Power Management if so.
 # You want the number of seconds to be ~10 seconds less than the time it takes
 # your screensaver or Power Management to activate.
@@ -313,7 +313,7 @@ while [ ! -z $1 ]; do
         "-h" | "--help" )
             help && exit 0;;
         * )
-            echo "Ivalid argument. See -h, --help for more information." && exit 1;;
+            echo "Invalid argument. See -h, --help for more information." && exit 1;;
     esac
     
     # arguments must be always passed in tuples
